const groups=[{name:'きほんの もじ',chars:'アイウエオカキクケコサシスセソタチツテトナニヌネノハヒフヘホマミムメモヤユヨラリルレロワヲン'},{name:'てん・まるの もじ',chars:'ガギグゲゴザジズゼゾダヂヅデドバビブベボパピプペポ'},{name:'ちいさい もじ',chars:'ァィゥェォャュョッ'},{name:'ことば',words:['アイス','カメラ','テレビ','バナナ','パンダ','パン','バス','ネコ','ケーキ','ジュース','シャツ','ベッド','ロボット','チョコ','ボール']}];
const app=document.querySelector('#app');let mode='learn',group=0,selected='ア',quiz=[],qi=0,score=0,answered=false,retried=false;
const hira=s=>[...s].map(c=>c>='ァ'&&c<='ヶ'?String.fromCharCode(c.charCodeAt(0)-96):c).join('');const pool=()=>groups[group].words||[...groups[group].chars];
function speak(s){const status=document.querySelector('#voice-status');if(!('speechSynthesis'in window)){if(status)status.textContent='この ききでは おとが でません。もじを みて よもう。';return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(s);u.lang='ja-JP';u.rate=.75;u.onerror=()=>{if(status)status.textContent='おとが でないときは、もじを みて よもう。'};speechSynthesis.speak(u)}
function shuffle(a){return a.slice().sort(()=>Math.random()-.5)}
function groupSelect(){return '<select aria-label="れんしゅうする もじ">'+groups.map((g,i)=>`<option value="${i}" ${i===group?'selected':''}>${g.name}</option>`).join('')+'</select>'}
function render(){
 writingCleanup();
 document.querySelectorAll('nav button').forEach(b=>{b.classList.toggle('active',b.dataset.mode===mode);b.setAttribute('aria-pressed',b.dataset.mode===mode)});
 if(mode==='quiz'){renderQuiz();return}
 if(mode==='write'){renderWriting();return}
 app.innerHTML=`<div class="surface"><div class="sectionhead"><h2>もじを タッチして みよう</h2>${groupSelect()}</div><div class="learn-layout"><div class="letter-card"><div class="big" style="${selected.length>1?'font-size:48px':''}">${selected}</div><div class="reading">${hira(selected)}</div><button class="primary" id="listen">♪ おとを きく</button></div><div class="grid">${pool().map(k=>`<button class="kana ${k===selected?'selected':''}" data-k="${k}" aria-label="${k}、${hira(k)}" style="${k.length>1?'font-size:19px':''}">${k}<small>${hira(k)}</small></button>`).join('')}</div></div><div class="muted" id="voice-status" aria-live="polite"></div></div>`;
 app.querySelector('.sectionhead select').onchange=e=>{group=+e.target.value;selected=pool()[0];render()};
 document.querySelector('#listen').onclick=()=>speak(selected);
 document.querySelectorAll('[data-k]').forEach(b=>b.onclick=()=>{selected=b.dataset.k;render()});
}
function startQuiz(){quiz=shuffle(pool()).slice(0,5).map(answer=>({answer,options:shuffle([answer,...shuffle(pool().filter(x=>x!==answer)).slice(0,3)])}));qi=0;score=0;answered=false;retried=false;renderQuiz()}
function renderQuiz(){if(!quiz.length){startQuiz();return}if(qi===quiz.length){app.innerHTML=`<div class="surface quiz"><div class="result-star">★</div><h2>さいごまで がんばったね！</h2><p class="question">${score} / ${quiz.length}</p><p>いっかいで できた もんだいの かず</p><p class="hint">まちがえた もじも、れんしゅうすると おぼえられるよ。</p><button class="primary" id="again">もういちど あそぶ</button></div>`;document.querySelector('#again').onclick=startQuiz;return}const q=quiz[qi];app.innerHTML=`<div class="surface"><div class="sectionhead"><h2>カタカナを えらぼう</h2>${groupSelect()}</div><div class="quiz"><div class="muted">${qi+1} / ${quiz.length} もん</div><div class="progress"><i style="width:${qi/quiz.length*100}%"></i></div><p>「${hira(q.answer)}」は どれかな？</p><div class="question">${hira(q.answer)}</div><div class="choices">${q.options.map(k=>`<button data-answer="${k}">${k}</button>`).join('')}</div><div class="feedback" aria-live="polite" id="feedback">ゆっくり えらんでね。</div><button class="primary" id="next" hidden>つぎへ →</button></div></div>`;app.querySelector('select').onchange=e=>{group=+e.target.value;selected=pool()[0];startQuiz()};app.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{if(answered)return;if(b.dataset.answer===q.answer){answered=true;if(!retried)score++;b.classList.add('correct');document.querySelector('#feedback').textContent='○ せいかい！ '+q.answer+' だね。';app.querySelectorAll('[data-answer]').forEach(x=>x.disabled=true);document.querySelector('#next').hidden=false;document.querySelector('#next').focus()}else{retried=true;b.classList.add('wrong');b.disabled=true;document.querySelector('#feedback').textContent='おしい！ もういちど えらんでみよう。'}});document.querySelector('#next').onclick=()=>{qi++;answered=false;retried=false;renderQuiz()}}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;if(mode==='quiz')quiz=[];render()});render();
