const strokeColors=['#d63583','#2474cd','#db7817','#258448','#854bc0','#805535'];
const strokeNames=['ピンク','あお','オレンジ','みどり','むらさき','ちゃいろ'];
let writingCleanup=()=>{},wordIndex=0;
function renderWriting(){writingCleanup();const chars=[...selected];if(wordIndex>=chars.length)wordIndex=0;const char=chars[wordIndex],strokes=characterStrokes(char);const pathHTML=(p,i,extra='')=>`<path d="${p.d}" transform="${p.transform||''}" stroke="${strokeColors[i]}" ${extra}/>`;
app.innerHTML=`<div class="surface"><div class="sectionhead"><h2>かきじゅんを みて、かこう</h2>${groupSelect()}</div><div class="write-layout"><div><label for="letter">かく もじを えらぼう</label><p><select id="letter">${pool().map(k=>`<option ${k===selected?'selected':''}>${k}</option>`).join('')}</select></p>${chars.length>1?`<div class="word-letters" aria-label="ことばの もじ">${chars.map((c,i)=>`<button data-char="${i}" aria-pressed="${i===wordIndex}">${c}</button>`).join('')}</div><p class="muted">1もじずつ れんしゅうしよう。</p>`:''}<div class="stroke-legend">${strokes.map((p,i)=>`<div><span style="background:${strokeColors[i]}">${i+1}</span>${i+1}かくめ：${strokeNames[i]}</div>`).join('')}</div><p class="muted hint">ゆびを はなすと、つぎの いろに かわるよ。</p></div><div><div class="writing-boards"><div><h3>① かきじゅんを みよう</h3><div class="board"><svg id="demo" viewBox="0 0 100 100" role="img" aria-label="${char}の かきじゅん"><g fill="none" stroke-width="4" stroke-linecap="round" stroke-linejoin="round">${strokes.map((p,i)=>pathHTML(p,i,'opacity=".17"')).join('')}${strokes.map((p,i)=>pathHTML(p,i,'class="animated-stroke" pathLength="1" stroke-dasharray="1" stroke-dashoffset="1"')).join('')}</g><circle id="pen-tip" r="2.5" fill="#183c40" visibility="hidden"/></svg></div><div class="actions"><button class="primary" id="play">▶ さいせい</button><button class="secondary" id="step">1かくずつ</button><button class="secondary" id="stop" disabled>とめる</button></div><p class="muted" id="animation-status" aria-live="polite">${char}は ${strokes.length}かく。うごきを みよう。</p></div><div><h3>② おなじ いろで なぞろう</h3><div class="board"><svg id="trace-guide" viewBox="0 0 100 100" aria-hidden="true"><g fill="none" stroke-width="4" stroke-linecap="round" stroke-linejoin="round" opacity=".23">${strokes.map((p,i)=>pathHTML(p,i)).join('')}</g><g id="start-numbers"></g></svg><canvas width="800" height="800" aria-label="${char}を なぞる らん"></canvas></div><p class="stroke-now" id="stroke-now" aria-live="polite"></p><div class="actions"><button class="secondary" id="undo">1かく もどす</button><button class="secondary" id="clear">ぜんぶ けす</button><button class="primary" id="done">かけた！</button></div><div class="feedback" id="write-status" aria-live="polite"></div></div></div><p class="muted">もじの かたちや かきじゅんの じどうさいてんは しません。</p></div></div></div>`;
app.querySelector('.sectionhead select').onchange=e=>{group=+e.target.value;selected=pool()[0];wordIndex=0;render()};app.querySelector('#letter').onchange=e=>{selected=e.target.value;wordIndex=0;render()};app.querySelectorAll('[data-char]').forEach(b=>b.onclick=()=>{wordIndex=+b.dataset.char;render()});
const demoPaths=[...app.querySelectorAll('.animated-stroke')],tip=app.querySelector('#pen-tip'),status=app.querySelector('#animation-status');let frame=0,run=0,next=0,busy=false;const play=app.querySelector('#play'),step=app.querySelector('#step'),stop=app.querySelector('#stop');
function controls(v){busy=v;play.disabled=step.disabled=v;stop.disabled=!v}
function resetDemo(){demoPaths.forEach(p=>p.style.strokeDashoffset=1);next=0}
function cancel(){run++;cancelAnimationFrame(frame);tip.setAttribute('visibility','hidden');controls(false)}
function animateOne(i,token,after){const p=demoPaths[i],len=p.getTotalLength(),start=performance.now();status.textContent=`${i+1}かくめ：${strokeNames[i]}`;tip.setAttribute('visibility','visible');function tick(t){if(token!==run)return;const progress=Math.min(1,(t-start)/1200);p.style.strokeDashoffset=1-progress;const at=p.getPointAtLength(len*progress);const pt=new DOMPoint(at.x,at.y).matrixTransform(p.transform.baseVal.consolidate()?.matrix||new DOMMatrix());tip.setAttribute('cx',pt.x);tip.setAttribute('cy',pt.y);if(progress<1)frame=requestAnimationFrame(tick);else{tip.setAttribute('visibility','hidden');next=i+1;after()}}frame=requestAnimationFrame(tick)}
play.onclick=()=>{cancel();resetDemo();controls(true);const token=run;function advance(){if(next<strokes.length)animateOne(next,token,advance);else{controls(false);status.textContent='おわり！ おなじ じゅんばんで かいてみよう。'}}advance()};
step.onclick=()=>{if(busy)return;if(next>=strokes.length)resetDemo();controls(true);animateOne(next,run,()=>{controls(false);status.textContent=next===strokes.length?'さいごまで みられたね！':`${next}かくめ まで。もういちど おすと つぎへ。`})};stop.onclick=()=>{cancel();resetDemo();status.textContent='とめたよ。はじめから みられるよ。'};
const ns='http://www.w3.org/2000/svg';demoPaths.forEach((p,i)=>{const raw=p.getPointAtLength(0),pt=new DOMPoint(raw.x,raw.y).matrixTransform(p.transform.baseVal.consolidate()?.matrix||new DOMMatrix());const g=document.createElementNS(ns,'g'),circle=document.createElementNS(ns,'circle'),text=document.createElementNS(ns,'text');circle.setAttribute('cx',pt.x);circle.setAttribute('cy',pt.y-5);circle.setAttribute('r',4.4);circle.setAttribute('fill',strokeColors[i]);text.setAttribute('x',pt.x);text.setAttribute('y',pt.y-3.4);text.setAttribute('text-anchor','middle');text.setAttribute('font-size','5');text.setAttribute('font-weight','bold');text.setAttribute('fill','white');text.textContent=i+1;g.append(circle,text);app.querySelector('#start-numbers').append(g)});
const canvas=app.querySelector('canvas'),ctx=canvas.getContext('2d');let ink=[],active=null,pointer=null;const undo=app.querySelector('#undo'),now=app.querySelector('#stroke-now'),feedback=app.querySelector('#write-status');
function redraw(){ctx.clearRect(0,0,800,800);[...ink,...(active?[active]:[])].forEach((points,i)=>{ctx.strokeStyle=strokeColors[i];ctx.fillStyle=strokeColors[i];ctx.lineWidth=13;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(...points[0]);points.slice(1).forEach(p=>ctx.lineTo(...p));ctx.stroke();if(points.length===1){ctx.beginPath();ctx.arc(...points[0],6.5,0,Math.PI*2);ctx.fill()}});undo.disabled=ink.length===0;const i=ink.length;now.textContent=i<strokes.length?`${i+1}かくめ：${strokeNames[i]}で かこう`:'ぜんぶ かけたね。おてほんと くらべよう！';now.style.color=strokeColors[Math.min(i,strokes.length-1)]}
function point(e){const r=canvas.getBoundingClientRect();return[(e.clientX-r.left)*800/r.width,(e.clientY-r.top)*800/r.height]}
canvas.onpointerdown=e=>{if(pointer!==null||ink.length>=strokes.length||e.button!==0)return;pointer=e.pointerId;canvas.setPointerCapture(pointer);active=[point(e)];feedback.textContent='';redraw()};canvas.onpointermove=e=>{if(e.pointerId!==pointer)return;active.push(point(e));redraw()};canvas.onpointerup=e=>{if(e.pointerId!==pointer)return;active.push(point(e));ink.push(active);active=null;pointer=null;redraw()};canvas.onpointercancel=canvas.onlostpointercapture=()=>{if(pointer===null)return;active=null;pointer=null;redraw()};undo.onclick=()=>{if(pointer!==null)return;ink.pop();feedback.textContent='';redraw()};app.querySelector('#clear').onclick=()=>{ink=[];active=null;pointer=null;feedback.textContent='';redraw()};app.querySelector('#done').onclick=()=>{feedback.textContent=ink.length<strokes.length?'まだ かいていない いろが あるよ。つづけて みよう。':'れんしゅう できたね！ おてほんと くらべて みよう。'};writingCleanup=cancel;redraw();
}
